### ISSUE TITLE
Leave node meta-data

### ISSUE THREAD

**Issue by dennis-tra** [guillaumemichel/py-binary-trie#1]
When we will analyse the graph parameters we will need to map PeerID -> Byte representation -> BitString representation -> insert in Trie. When we then want to check the closest entries in the Trie to a particular PeerID we would only get the BitString representation from the Trie. This can be calculated to a Byte representation but not necessarily back to a PeerID because we don't know the multicodec that produced the Bytes. Hence my feature request: it would be great if we could attach meta data to leave nodes :)

**Comment by guillaumemichel** [comment]
Good point! Thank you for the suggestion!

The `Trie` object will additionally contain a `metadata` attribute, that could contain a variable/object.

Does the following design look good to you @dennis-tra?

```python
class Trie(object):
    def __init__(self, metadata=None, key=""):
        self.metadata=metadata
        ...

    def add(self, key, metadata=None) -> bool:
        ...
        newly_created_node = Trie(metadata=metadata, key=key)
        ...

    def find(self, key):
        ...
        if key in trie:
            if self.metadata is None:
                return True
            else:
                return self.metadata
        else:
            return False

    def n_closest(self, key, n:int) -> list[]:
        ...
        return [node.metadata if node.metadata is not None else node.key for node in nClosestNodesToKey]
```
